# The URL the site will be built for
base_url = "https://u64.cam"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

theme = "apollo"

build_search_index = false
generate_feed = true
minify_html = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
toc = true
use_cdn = false

menu = [
    { name = "/about", url = "/about", weight = 1 },
    { name = "/photos", url = "/photos", weight = 2 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/posts", url = "/posts", weight = 3 },
]

socials = [
    { name = "github", url = "https://github.com/camerondurham/", icon = "github" },
    { name = "stackoverflow", url = "https://stackoverflow.com/users/4676641/cam", icon="stack-overflow" },
    { name = "linkedin", url = "https://www.linkedin.com/in/cameron-durham/", icon = "linkedin" },
    { name = "spotify", url = "https://open.spotify.com/user/mnakgi5690zc9bqpbyk8z59ma", icon = "spotify" },
    { name = "instagram", url = "https://www.instagram.com/u64.cam/", icon = "instagram" },
    { name = "discord", url = "https://discordapp.com/users/632337069955612703/", icon = "discord" },
    { name = "steam", url = "https://steamcommunity.com/profiles/76561198314787235/", icon = "steam" },
]

custom_css = [

]

[extra.analytics]
enabled = true
goatcounter_user = "u64cam"
