set -g mode-keys vi
set -g history-limit 10000
set-option -sg escape-time 10
set-option -g default-terminal "screen-256color"

# use | and - to split windows
bind-key \ split-window -h -c '#{pane_current_path}'
bind-key - split-window -v -c '#{pane_current_path}'
unbind '"'
unbind %

# reload the conf file on the fly
bind r source-file ~/.tmux.conf

# repeat last shell command on right pane (if it happens to be a shell)
bind-key u select-pane -t 1 \; send-keys C-c Up C-m \; last-pane

# tmux conf from https://github.com/wincent/wincent/blob/aa3a322e3a911dabe0ef398ebb1fd7c77209b8ac/roles/dotfiles/files/.tmux.conf
# Resizing (mouse also works).
unbind Left
bind -r Left resize-pane -L 5
unbind Right
bind -r Right resize-pane -R 5
unbind Down
bind -r Down resize-pane -D 5
unbind Up
bind -r Up resize-pane -U 5


# moving between windows with vim movement keys
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# y and p as in vim
bind Escape copy-mode
unbind p
bind p paste-buffer
